@startuml StartRequest
start
repeat
repeat while (Start request received) is (No);
->Yes;
fork
    if(Engine ready to start?) then (Yes)
        :EngSt = On;
    else(No)
        :EngSt = Previous state;
    endif
fork again
    if(Gearbox ready to start?) then (Yes)
        :GearBoxSt = Rdy;
    else(No)
        :GearBoxSt = NotRdy;
    endif
end fork
stop
@enduml